SELECT c.NAME, COUNT(p.ID) AS PROJECT_COUNT
FROM client c
JOIN project p ON c.ID = p.CLIENT_ID
GROUP BY c.ID, c.NAME
HAVING COUNT(p.ID) IN (
    SELECT COUNT(ID)
    FROM project
    GROUP BY CLIENT_ID
    ORDER BY 1 DESC
    LIMIT ?
);